### ISSUE TITLE
Packaging Roadmap & To-dos

### ISSUE THREAD

**Issue by tanneberger** [lf-lang/lingo#48]
This is the issue tracker for progress for the Task **"Lingua-Franca Packages"**.

We highly encourage the entire community to participate in this effort, by testing, using or even better implementing the different points listed below. 

**LFC**
- [ ] Import Syntax
  - [ ] Updating the Grammar
- [ ] Dynamic Search Paths
  - [ ] Telling LFC where the library directory is located 
  - [ ] LFC load sources from that location

**LINGO**
- [ ] Recursive Fetching
  - [ ] Pull & Parse 
  - [ ] Data Structure for this dependency tree 
- [ ] Package Selection 
  - [ ] Dependency Tree Flattening 
  - [ ] Removal of unused packages
  
Please assign yourself tasks by editing this issue.
